/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
    "./node_modules/@material-tailwind/react/components/**/*.{js,jsx}",
    "./node_modules/@material-tailwind/react/theme/components/**/*.{js,jsx}",
  ],
  mode: "jit",
  theme: {
    extend: {
      colors: {
        primary: "#a9ff5c",
        secondary: "#f1fbe8",
        primarylight: "#e1ffc7",
        textblack: "#090d06",
        paragrey: "#979f90",
        primarydark: "#356905",
        lightback: "#426027",
        greyfont: "#979f90",
        primaryhover: "#7fd136",
        lightOrange: "#ffc295",
        darkOrange: "#602606",
        lightyellow: "#ffe27d",
        darkyellow: "#564801",
        darkgreen1: "#003800",
        darkgreen2: "#002d00",
        darkgreenop10: "#1f2b15",
        footerc: "#131c0b",
      },
      fontFamily: {
        Nunito: ["Nunito Sans", "sans-serif"],
        Borel: ["Borel", "cursive"],
        orbitron: ["Orbitron", " sans-serif"],
        Futura_pt: ["Futurapt", "sans-serif"],
        Futura_ptex: ["Futuraptex", "sans-serif"],
        Ttravelm: ["Ttravelm", "sans-serif"],
        TTravelr: ["TTravelr", "sans-serif"],
        TTravele: ["TTravele", "sans-serif"],
        TTravelb: ["TTravelb", "sans-serif"],
      },
    },
    screens: {
      xs: "480px",
      ss: "620px",
      sm: "768px",
      vmd: "930px",
      md: "1060px",
      lg: "1200px",
      xl: "1700px",
    },
  },
  plugins: [],
};
